### PR TITLE
Version 0.14

### PR DESCRIPTION
**Pull request by javaduke**

### CODE REVIEW

**Comment by javaduke** [comment]
The TravisCI checks are failing apparently because it uses the wrong version of Gradle (not 2.14), but I don't know how to fix it.

**Comment by jeffbowman** [comment]
Gradle 2.14 is really ancient, any chance to upgrade the version of Gradle to something more current? Not a TravisCI expert, but this page seems to indicate Gradle 4.0 is used: https://docs.travis-ci.com/user/reference/trusty/

**Comment by javaduke** [comment]
@machaval Mariano, any chance you can migrate it to the newer version of Gradle (since you are an expert)?

**Comment by javaduke** [comment]
ok, problem solved. I hate gradle.

**Pull request merged**
